In [1]:
## Import numpy as `np` and print the version number
import numpy as np
np.__version__

'1.16.2'

In [2]:
##Create a 1D array of numbers from 0 to 9
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
##3. How to create a boolean array?
np.full((3*3),True,dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [7]:
np.ones((3*3),dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
##Q. Extract all odd numbers from arr
arr[arr %2 !=0]

array([1, 3, 5, 7, 9])

In [13]:
##Q. Replace all odd numbers in arr with -1
arr[arr %2 !=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
##Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out=np.where(arr%2!=0,-1,arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
## Q. Convert a 1D array to a 2D array with 2 rows
arr=np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
##Q. Stack arrays a and b vertically
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
c=np.concatenate((a,b),axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
##9. How to stack two arrays horizontally?
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
c=np.concatenate((a,b),axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [48]:
##Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a=np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])