In [47]:
import numpy as np

In [74]:
a=np.array([[10,20,30],[40,55,69],[75,80,999]])
a

array([[ 10,  20,  30],
       [ 40,  55,  69],
       [ 75,  80, 999]])

In [75]:
a[0,0]

10

In [76]:
a[0,2]

30

In [77]:
a[[0,0]]

array([[10, 20, 30],
       [10, 20, 30]])

In [78]:
a[[0,2]]

array([[ 10,  20,  30],
       [ 75,  80, 999]])

In [79]:
a[[0]]

array([[10, 20, 30]])

In [80]:
a[[1]]

array([[40, 55, 69]])

In [81]:
a[[2]]

array([[ 75,  80, 999]])

In [82]:
a[[0,1,2]]

array([[ 10,  20,  30],
       [ 40,  55,  69],
       [ 75,  80, 999]])

In [83]:
a[[1,2]]

array([[ 40,  55,  69],
       [ 75,  80, 999]])

In [84]:
a[[2,1]]

array([[ 75,  80, 999],
       [ 40,  55,  69]])

In [85]:
a[[2,-1]]

array([[ 75,  80, 999],
       [ 75,  80, 999]])

In [86]:
a[[-2,-1]]

array([[ 40,  55,  69],
       [ 75,  80, 999]])

In [87]:
a[[-2,1]]

array([[40, 55, 69],
       [40, 55, 69]])

In [88]:
a[[-2,1],[-1,2]]

array([69, 69])

In [89]:
a[[0,-1],[-2,0]]

array([20, 75])

In [90]:
a[[[0,-1]],[[0,-1],[0,0]]]

array([[ 10, 999],
       [ 10,  75]])

In [91]:
a[[[0,-2]],[[0,-2],[0,0]]]

array([[10, 55],
       [10, 40]])

In [92]:
a[[[0,-2]],[[0,-2],[0,0],[0,-1]]]

array([[10, 55],
       [10, 40],
       [10, 69]])

In [93]:
a[[[0,-2]],[[0,-2],[0,0],[0,-2]]]

array([[10, 55],
       [10, 40],
       [10, 55]])

In [94]:
a[[[0,-1]],[[0,-1],[0,0],[0,-2]]]

array([[ 10, 999],
       [ 10,  75],
       [ 10,  80]])

In [95]:
a[[[0,-1]],[[0,-1],[0,1],[0,-0]]]

array([[ 10, 999],
       [ 10,  80],
       [ 10,  75]])

In [96]:
a[[[0,0]],[[0,0],[0,1],[0,2]]]

array([[10, 10],
       [10, 20],
       [10, 30]])

In [97]:
a[[[0,1]],[[0,0],[0,1],[0,2]]]

array([[10, 40],
       [10, 55],
       [10, 69]])

In [98]:
a[[[0,2]],[[0,0],[0,1],[0,2]]]

array([[ 10,  75],
       [ 10,  80],
       [ 10, 999]])

In [99]:
a[:,2]

array([ 30,  69, 999])

In [100]:
a[:,1]

array([20, 55, 80])

In [101]:
a[:,0]

array([10, 40, 75])

In [102]:
a[[0,1,2],[0,1,2]]

array([ 10,  55, 999])

In [103]:
a[[0,1,2],[2,1,0]]

array([30, 55, 75])

In [104]:
a[-1:-2:-3]

array([[ 75,  80, 999]])

In [105]:
a[::-1,2:1:-1]

array([[999],
       [ 69],
       [ 30]])

In [106]:
a[::-1,2:0:-1]

array([[999,  80],
       [ 69,  55],
       [ 30,  20]])