In [17]:
import numpy as np

In [18]:
a=np.arange(15).reshape(5,3)

In [19]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# INDEXING WITH BOOLEAN VALUES:

In [20]:
a>=6

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
a<6

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [22]:
a<=6

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [23]:
b=a>=5

In [24]:
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a[b]=100

In [30]:
a

array([[  0,   1,   2],
       [  3,   4, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [31]:
a.itemsize

4

In [32]:
a=np.arange(15)

In [33]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)

In [36]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [37]:
a.itemsize

8

In [48]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)

In [49]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [42]:
a=np.array([[1,2],[3,4],[5,6]],dtype=list)

In [43]:
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=object)

In [50]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [54]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.eye((50))

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [58]:
a=np.linspace(2,4,8)

In [59]:
a

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [60]:
a=np.linspace(10,12,14)

In [61]:
a

array([10.        , 10.15384615, 10.30769231, 10.46153846, 10.61538462,
       10.76923077, 10.92307692, 11.07692308, 11.23076923, 11.38461538,
       11.53846154, 11.69230769, 11.84615385, 12.        ])

In [62]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [63]:
np.linspace(2,4,6)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [64]:
a.ravel()

array([10.        , 10.15384615, 10.30769231, 10.46153846, 10.61538462,
       10.76923077, 10.92307692, 11.07692308, 11.23076923, 11.38461538,
       11.53846154, 11.69230769, 11.84615385, 12.        ])

In [72]:
x=np.arange(10).reshape(2,5)

ravelled_array=x.ravel() # changes in the original content

ravelled_array[4]=100

ravelled_array


array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [73]:
x

array([[  0,   1,   2,   3, 100],
       [  5,   6,   7,   8,   9]])

In [76]:
y=np.arange(10).reshape(5,2)

ravelled_array=y.ravel() # changes in the original content

ravelled_array[4]=100

ravelled_array


array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [77]:
y

array([[  0,   1],
       [  2,   3],
       [100,   5],
       [  6,   7],
       [  8,   9]])

In [78]:
x=np.arange(9).reshape(3,3)

flattened_array=x.flatten() # doesnt change in original content.

flattened_array[5]=100

flattened_array


array([  0,   1,   2,   3,   4, 100,   6,   7,   8])

In [79]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
y=np.arange(36).reshape(6,6)

flattened_array=y.flatten() # doesnt change in original content.

flattened_array[5]=100

flattened_array


array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35])

In [81]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
x=np.arange(9).reshape(3,3)
x.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [85]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [84]:
y=np.arange(36).reshape(6,6)
y.transpose()

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [86]:
y.T

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [87]:
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
y.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [89]:
np.resize(x,(7,7))

array([[0, 1, 2, 3, 4, 5, 6],
       [7, 8, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8, 0],
       [1, 2, 3, 4, 5, 6, 7],
       [8, 0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2, 3]])

In [90]:
np.resize(y,(7,7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11, 12]])

In [91]:
x.min

<function ndarray.min>

In [92]:
x.min()

0

In [93]:
x.max

<function ndarray.max>

In [94]:
x.max()

8

In [95]:
x.sum

<function ndarray.sum>

In [96]:
x.sum()

36

In [97]:
x.squeeze

<function ndarray.squeeze>

In [98]:
x.squeeze()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
x.std

<function ndarray.std>

In [100]:
x.std()

2.581988897471611

In [101]:
x.mean

<function ndarray.mean>

In [102]:
x.mean()

4.0

In [103]:
np.sqrt(x)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [104]:
x.sum(axis=0)

array([ 9, 12, 15])

In [105]:
x.sum(axis=1)

array([ 3, 12, 21])

In [106]:
np.resize(y,(7,7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11, 12]])

In [107]:
y.min()

0

In [109]:
y.max()

35

In [110]:
y.sum()

630

In [111]:
y.squeeze()

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [113]:
y.std()

10.388294694831615

In [114]:
y.mean()

17.5

In [115]:
np.sqrt(y)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262,
        5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978]])

In [116]:
y.sum(axis=0)

array([ 90,  96, 102, 108, 114, 120])

In [117]:
y.sum(axis=1)

array([ 15,  51,  87, 123, 159, 195])

In [118]:
u=np.array([[1,2],[3,4]])

In [119]:
v=np.array([[5,6],[7,8]])

In [120]:
u+v

array([[ 6,  8],
       [10, 12]])

In [121]:
u+v

array([[ 6,  8],
       [10, 12]])

In [122]:
v-u

array([[4, 4],
       [4, 4]])

In [123]:
v.dot(u)

array([[23, 34],
       [31, 46]])