In [1]:
import numpy as np

In [2]:
d=np.array([[2,4,6],[8,10,12],[14,16,18]])

In [3]:
d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
for row in d:
    print(row)

[2 4 6]
[ 8 10 12]
[14 16 18]


In [6]:
for column in d:
    print(column)

[2 4 6]
[ 8 10 12]
[14 16 18]


In [7]:
for cell in d.flat:
    print(cell)

2
4
6
8
10
12
14
16
18


In [15]:
f=np.arange(8).reshape(2,4)

In [16]:
f

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
f=np.arange(9).reshape(3,3)

In [19]:
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# STACKING:

In [20]:
np.vstack((d,f))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.hstack((d,f))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [23]:
d=np.arange(40).reshape(2,20)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [24]:
f=np.arange(30).reshape(2,15)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
d=np.arange(40).reshape(5,4,2)
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

# SPLITTING:

In [64]:
np.hsplit(f,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [65]:
q=np.hsplit(f,3)

In [66]:
q[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [67]:
q[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [68]:
q[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [69]:
q[0::]

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [70]:
q[0::2]

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [71]:
q[0::-1]

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]])]

In [72]:
q[1::-2]

[array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]])]

In [73]:
q[2::-3]

[array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [74]:
q[-1::-1]

[array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]])]

In [75]:
q[-1::-2]

[array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]]), array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]])]

In [76]:
q[-1::-3]

[array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [77]:
q[1::-1]

[array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]])]

In [78]:
q[1::-2]

[array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]])]

In [79]:
q[1::-3]

[array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]])]

In [80]:
q[3:-2:-1]

[array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [81]:
q[-2:-1]

[array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]])]

In [82]:
q=np.hsplit(f,5)

In [83]:
q[0::]

[array([[ 0,  1,  2],
        [15, 16, 17]]), array([[ 3,  4,  5],
        [18, 19, 20]]), array([[ 6,  7,  8],
        [21, 22, 23]]), array([[ 9, 10, 11],
        [24, 25, 26]]), array([[12, 13, 14],
        [27, 28, 29]])]

In [84]:
q[1::-3]

[array([[ 3,  4,  5],
        [18, 19, 20]])]

In [85]:
q[1::-2]

[array([[ 3,  4,  5],
        [18, 19, 20]])]

In [86]:
q[-1::-2]

[array([[12, 13, 14],
        [27, 28, 29]]), array([[ 6,  7,  8],
        [21, 22, 23]]), array([[ 0,  1,  2],
        [15, 16, 17]])]

In [87]:
q[2::-3]

[array([[ 6,  7,  8],
        [21, 22, 23]])]

In [88]:
q[3:2:-4]

[array([[ 9, 10, 11],
        [24, 25, 26]])]

In [ ]:
q[3:-2]