In [1]:
import numpy as np

In [2]:
c=np.array([[[30,35,40],[40,45,50],[50,55,60]],[[110,222,333],[440,555,660],[771,882,993]],[[1111,2222,3333],[4444,5555,6666],[7777,8888,9999]]])

In [3]:
c.ndim

3

In [4]:
c.shape

(3, 3, 3)

In [5]:
c.size

27

In [6]:
c.itemsize

4

In [7]:
c

array([[[  30,   35,   40],
        [  40,   45,   50],
        [  50,   55,   60]],

       [[ 110,  222,  333],
        [ 440,  555,  660],
        [ 771,  882,  993]],

       [[1111, 2222, 3333],
        [4444, 5555, 6666],
        [7777, 8888, 9999]]])

In [8]:
c[0]

array([[30, 35, 40],
       [40, 45, 50],
       [50, 55, 60]])

In [9]:
c[1]

array([[110, 222, 333],
       [440, 555, 660],
       [771, 882, 993]])

In [10]:
c[2]

array([[1111, 2222, 3333],
       [4444, 5555, 6666],
       [7777, 8888, 9999]])

In [11]:
c[0,0]

array([30, 35, 40])

In [12]:
c[0,1]

array([40, 45, 50])

In [13]:
c[0,2]

array([50, 55, 60])

In [14]:
c[0,0,0]

30

In [15]:
c[0,1,0]

40

In [16]:
c[0,1,1]

45

In [17]:
c[1,1,1]

555

In [18]:
c[1,0,1]

222

In [19]:
c[1,1,2]

660

In [20]:
c[2,1,1]

5555

In [21]:
c[2,1,2]

6666

In [22]:
c[2,2,2]

9999

In [23]:
c[[0,1,2],[0,1,2]]

array([[  30,   35,   40],
       [ 440,  555,  660],
       [7777, 8888, 9999]])

In [24]:
c[[0,1,2],[2,1,2]]

array([[  50,   55,   60],
       [ 440,  555,  660],
       [7777, 8888, 9999]])

In [26]:
c[[0,1,2],[2,1,1]]

array([[  50,   55,   60],
       [ 440,  555,  660],
       [4444, 5555, 6666]])

In [28]:
c[:,1,:]

array([[  40,   45,   50],
       [ 440,  555,  660],
       [4444, 5555, 6666]])

In [29]:
c[:,0,:]

array([[  30,   35,   40],
       [ 110,  222,  333],
       [1111, 2222, 3333]])

In [30]:
c[:,2,:]

array([[  50,   55,   60],
       [ 771,  882,  993],
       [7777, 8888, 9999]])

In [33]:
c[2,::,:]

array([[1111, 2222, 3333],
       [4444, 5555, 6666],
       [7777, 8888, 9999]])

In [34]:
c[:,:,0]

array([[  30,   40,   50],
       [ 110,  440,  771],
       [1111, 4444, 7777]])

In [35]:
c[:,:,1]

array([[  35,   45,   55],
       [ 222,  555,  882],
       [2222, 5555, 8888]])

In [36]:
c[:,:,2]

array([[  40,   50,   60],
       [ 333,  660,  993],
       [3333, 6666, 9999]])

In [38]:
c[[0,1,2],[2,1,0]]

array([[  50,   55,   60],
       [ 440,  555,  660],
       [1111, 2222, 3333]])

In [40]:
c[[0,1,2],[1,0,2]]

array([[  40,   45,   50],
       [ 110,  222,  333],
       [7777, 8888, 9999]])

In [41]:
c[[1,0,2],[1,0,2]]

array([[ 440,  555,  660],
       [  30,   35,   40],
       [7777, 8888, 9999]])

In [42]:
c[[0],[0,1,2]]

array([[30, 35, 40],
       [40, 45, 50],
       [50, 55, 60]])

In [43]:
c[[0],[0,1,2],[2,1,0]]

array([40, 45, 50])

In [44]:
c[[0],[0,1,2],[0,1,2]]

array([30, 45, 60])

In [45]:
c[[0,1,2],[0,1,2]]

array([[  30,   35,   40],
       [ 440,  555,  660],
       [7777, 8888, 9999]])

In [46]:
c[[1],[0,1,2]]

array([[110, 222, 333],
       [440, 555, 660],
       [771, 882, 993]])

In [47]:
c[[1],[0,1,2],[2,1,0]]

array([333, 555, 771])

In [50]:
c[[1],[0,1,2],[0,1,2]]

array([110, 555, 993])

In [49]:
c[[2],[0,1,2]]

array([[1111, 2222, 3333],
       [4444, 5555, 6666],
       [7777, 8888, 9999]])

In [51]:
c[[2],[0,1,2],[2,1,0]]

array([3333, 5555, 7777])

In [52]:
c[[2],[0,1,2],[0,1,2]]

array([1111, 5555, 9999])